### ISSUE TITLE
Sensors in Home Assistant all have the same name

### ISSUE THREAD

**Issue by RealGandy** [sascha432/hass_mqtt_raid_status#1]
I like this script, so thank you for creating and sharing, however, all sensors have the same name, whereas I would expect them to have suffixes such as:

- state
- total
- used
- free pct
- free 

![image](https://github.com/sascha432/hass_mqtt_raid_status/assets/305484/64b51eab-f61f-46cd-9c36-a517c96ebff1)

**Comment by sascha432** [comment]
I added the suffix to the names as well.
