### ISSUE TITLE
Free Percent is showing used percent

### ISSUE THREAD

**Issue by RealGandy** [sascha432/hass_mqtt_raid_status#2]
Note from image;

Total Size = 4.51 TB
Used = 1.09 TB
Free = 3.42 TB
Free Pct = 24.2%

Free Pct is showing used percent (1.09/4.51)*100
Free Pct should be (3.42/4.51)*100 = 75.8%

![image](https://github.com/sascha432/hass_mqtt_raid_status/assets/305484/117ff787-61b3-4cf3-9673-dd8fa9395772)

**Comment by sascha432** [comment]
Thanks for the report.

```
psutil.disk_usage()

return disk usage statistics about the partition which contains the given path as a named tuple including total, 
used and free space expressed in bytes, plus the percentage **usage**
```

Looks like I didn't pay attention and assumed after free space the percentage is free as well ;)
